"""Composite foreign key

Revision ID: 25c34b413e3a
Revises: 86e587d6ce3f
Create Date: 2016-10-19 18:58:57.412892

"""

# revision identifiers, used by Alembic.
revision = '25c34b413e3a'
down_revision = '86e587d6ce3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_item_in_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item_in_order_id')
    op.drop_table('items_in_orders')

    op.create_table('items_in_orders',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'order_id')
    )

    op.add_column('order_items', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))

    op.create_foreign_key(None, 'order_items', 'items_in_orders', ['item_id', 'order_id'], ['item_id', 'order_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_in_order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_item_in_order_id_fkey', 'order_items', 'items_in_orders', ['item_in_order_id'], ['id'])
    op.drop_column('order_items', 'order_id')
    op.drop_column('order_items', 'item_id')
    op.create_table('items_in_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='items_in_orders_item_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='items_in_orders_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_in_orders_pkey')
    )
    op.drop_table('items_in_orderss')
    ### end Alembic commands ###
