"""empty message

Revision ID: 86e587d6ce3f
Revises: 9f3231bcc346
Create Date: 2016-10-19 17:47:46.322849

"""

# revision identifiers, used by Alembic.
revision = '86e587d6ce3f'
down_revision = '9f3231bcc346'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_in_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('item_in_order_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_items_item_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'items_in_orders', ['item_in_order_id'], ['id'])
    op.drop_column('order_items', 'order_id')
    op.drop_column('order_items', 'payed')
    op.drop_column('order_items', 'item_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('payed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_items_item_id_fkey', 'order_items', 'items', ['item_id'], ['id'])
    op.drop_column('order_items', 'item_in_order_id')
    op.drop_table('items_in_orders')
    ### end Alembic commands ###
