"""Added order list table

Revision ID: 9f3231bcc346
Revises: a7f8c246e300
Create Date: 2016-09-07 15:54:43.648440

"""

# revision identifiers, used by Alembic.
revision = '9f3231bcc346'
down_revision = 'a7f8c246e300'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'orderlist', ['list_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'list_id')
    op.drop_table('orderlist')
    ### end Alembic commands ###
