"""Add foreign key

Revision ID: a1277ad6edf1
Revises: cacd775b7cf8
Create Date: 2016-10-19 19:05:07.101908

"""

# revision identifiers, used by Alembic.
revision = 'a1277ad6edf1'
down_revision = 'cacd775b7cf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    ### end Alembic commands ###
