"""Add foreign key

Revision ID: cacd775b7cf8
Revises: 25c34b413e3a
Create Date: 2016-10-19 19:04:45.718946

"""

# revision identifiers, used by Alembic.
revision = 'cacd775b7cf8'
down_revision = '25c34b413e3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'items', ['item_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    ### end Alembic commands ###
